name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_RELEASE_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx roamjs-scripts build 
      - name: publish
        run: npx roamjs-scripts publish
